### ISSUE TITLE
Ménage de *log.gz aussi

### ISSUE THREAD

**Issue by salaun-urennes1** [DSI-Universite-Rennes2/get-partage-logs#1]
Hello,

Je crois que la commande de ménage des logs doit être adaptée pour faire le méngae des logs gzippés aussi :
`find "${DESTDIR_LOG_NG}" -type f -name "*.log" -mtime +"${MAX_LOG_DAYS}"`

**Comment by salaun-urennes1** [comment]
Bonjour Yann,

Je constate que le ménage des logs ne fonctionne pas car il manque l'option `-delete` à la ligne suivante:
`find "${DESTDIR_LOG_NG}" -type f '(' -name "*.log" -o -name "*.log.gz" ')' -mtime +"${MAX_LOG_DAYS}"`

Par ailleurs, ça serait bien de supprimer les répertoires aussi, donc je propose plutôt:
`find "${DESTDIR_LOG_NG}" -mtime +"${MAX_LOG_DAYS}" -delete`

**Comment by Zeuh** [comment]
ah le coup du delete je pensais l'avoir commit/push mais j'en ai oublié un, c'est fixé !

**Comment by salaun-urennes1** [comment]
Super, merci
